Models/ConsultationModel.cs
using AspNetCoreConsultationForm.Settings;
using System;
using System.ComponentModel.DataAnnotations;

public class ConsultationModel
{
    [Required(ErrorMessage = "First and last name are required")]
    public string Name { get; set; }

    [Required(ErrorMessage = "Email is required")]
    [EmailAddress(ErrorMessage = "Please enter a valid Email")]
    public string Email { get; set; }

    [Required(ErrorMessage = "The desired consultation date is required")]
    [DataType(DataType.Date)]
    [FutureDate(ErrorMessage = "The desired date must be in the future")]
    [NotOnMonday(ErrorMessage = "The desired date must not be a weekend")]
    public DateTime ConsultationDate { get; set; }

    [Required(ErrorMessage = "Please select a product")]
    public string SelectedProduct { get; set; }
}

Models/ErrorViewModel.cs
namespace AspNetMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/FileViewModel.cs

namespace AspNetMVC.Models
{
    public class FileViewModel
    {
        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string FileName { get; set; }
    }

}

Models/OrderProduct.cs
namespace AspNetMVC.Models
{
    // Product.cs
    public class OrderProduct
    {
        public string Name { get; set; }
        public int Quantity { get; set; }
    }

}

Models/Product.cs
namespace AspNetMVC.Models
{
    // Product.cs
    public class Product
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public DateTime CreatedDate { get; set; }
    }

}

Models/ProductModel.cs
namespace AspNetMVC.Models
{
    public class ProductModel
    {

        public int ID { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }

    }
}

Models/User.cs
namespace AspNetMVC.Models
{
    // User.cs
    public class User
    {
        public string Name { get; set; }
        public int Age { get; set; }
        public List<OrderProduct> Products { get; set; }
    }

}

Models/WeatherModel.cs
using Newtonsoft.Json;
namespace AspNetMVC.Models
{
    public class WeatherModel
    {
        public string City { get; set; }
        public double Temperature { get; set; }
        public string WeatherDescription { get; set; }
        public string Weather { get; set; }
        public double Humidity { get; set; }
        public double WindSpeed { get; set; }
    }
}

Components/ProductViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using AspNetMVC.Models;

namespace AspNetMVC.Components
{
    public class ProductViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(List<ProductModel> products)

        {
            return View("/Views/Product/ProductTable.cshtml", products);

        }
    }
}

Components/WeatherViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using AspNetMVC.Models;

namespace AspNetMVC.Components
{
    public class WeatherViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(string region)
        {

            using (var httpClient = new HttpClient())
            {
                var apiKey = "c638570cd23c4637aaf32e116eeaceb7";
                var apiUrl = $"https://api.openweathermap.org/data/2.5/weather?q={region}&appid={apiKey}&units=metric";

                var response = await httpClient.GetAsync(apiUrl);

                if (response.IsSuccessStatusCode)
                {
                    var content = await response.Content.ReadAsStringAsync();
                    dynamic jsonObject = JsonConvert.DeserializeObject(content);

                    WeatherModel weather = new WeatherModel
                    {
                        City = jsonObject.name,
                        Temperature = jsonObject.main.temp,
                        Weather = jsonObject.weather[0].main,
                        WeatherDescription = jsonObject.weather[0].description,
                        Humidity = jsonObject.main.humidity,
                        WindSpeed = jsonObject.wind.speed,


                    };
                    return View("/Views/Product/Weather.cshtml", weather);
                }
            }

            return Content("Помилка отримання погоди");
        }

    }
}

Controllers/ConsultationController.cs
using Microsoft.AspNetCore.Mvc;
using AspNetMVC.Models;

public class ConsultationController : Controller
{
    public IActionResult Index()
    {
        return View();
    }

    [HttpPost]
    public string Consultation(ConsultationModel model)
    {
        if (ModelState.IsValid)
        {
            return $"Дані пройшли валідацію: {model.Name} - {model.Email} - {model.ConsultationDate} - {model.SelectedProduct}";
        }
        return "Дані не пройшли валідацію";
    }
}

Controllers/FileController.cs
using Microsoft.AspNetCore.Mvc;
using System.Text;

namespace AspNetMVC.Controllers
{
    public class FileController : Controller
    {
        private readonly IWebHostEnvironment _hostingEnvironment;

        public FileController(IWebHostEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> DownloadFile(string firstName, string lastName, string fileName)
        {
            // Переконайтесь, що fileName містить розширення .txt
            if (!fileName.EndsWith(".txt"))
            {
                fileName += ".txt";
            }

            var filePath = Path.Combine(_hostingEnvironment.WebRootPath, "downloads", fileName);

            var fileContent = $"Ім'я: {firstName}{Environment.NewLine}Прізвище: {lastName}";

            await System.IO.File.WriteAllTextAsync(filePath, fileContent, Encoding.UTF8);

            return PhysicalFile(filePath, "text/plain", fileName);
        }

    }
}

Controllers/HomeController.cs
using AspNetMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace AspNetMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;

namespace AspNetMVC.Controllers
{
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View("./Views/Product/Index.cshtml");
        }
    }
}

Views/Consultation/Index.cshtml
@model ConsultationModel

<h2>Форма Реєстрації на Консультацію</h2>

<form method="post" asp-controller="Consultation" asp-action="Consultation">
    <div class="form-group">
        <label asp-for="Name">Ім'я прізвище:</label>
        <input asp-for="Name" class="form-control" placeholder="required field for input" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Email">Email:</label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="ConsultationDate">Бажана дата консультації:</label>
        <input asp-for="ConsultationDate" type="date" class="form-control" />
        <span asp-validation-for="ConsultationDate" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="SelectedProduct">Виберіть продукт для консультації:</label>
        <select asp-for="SelectedProduct" class="form-control">
            <option value="">Select a product</option>
            <option value="JavaScript">JavaScript</option>
            <option value="C#">C#</option>
            <option value="Java">Java</option>
            <option value="Python">Python</option>
            <option value="Основи">Основи</option>
        </select>
        <span asp-validation-for="SelectedProduct" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Зареєструватися</button>
</form>

Views/File/Index.cshtml
@model AspNetMVC.Models.FileViewModel


<h2>Форма завантаження файлу</h2>

<form asp-controller="File" asp-action="DownloadFile" method="post">
    <div class="form-group">
        <label asp-for="FirstName">Ім'я:</label>
        <input asp-for="FirstName" class="form-control" required />
    </div>
    <div class="form-group">
        <label asp-for="LastName">Прізвище:</label>
        <input asp-for="LastName" class="form-control" required />
    </div>
    <div class="form-group">
        <label for="fileName">Назва файлу:</label>
        <input type="text" id="fileName" name="fileName" class="form-control" required />
    </div>
    <button type="submit" class="btn btn-primary">Продовжити</button>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Product/Index.cshtml
@using AspNetMVC.Models
@{

    List<ProductModel> products = new List<ProductModel>();


    products.Add(new ProductModel { ID = 1, Name = "Продукт 1", Price = 10.99M });
    products.Add(new ProductModel { ID = 2, Name = "Продукт 2", Price = 19.99M });
    products.Add(new ProductModel { ID = 3, Name = "Продукт 3", Price = 5.49M });

}
<!DOCTYPE html>
<html>
<head>
    <meta content="width=device-width" />
    <title>Завдання</title>
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body>
    <div>
        @await Component.InvokeAsync("Product", new {products=products})
    </div>
    <div>
        @await Component.InvokeAsync("Weather", new {region="Odesa"})
    </div>
</body>
</html>

Views/Product/ProductTable.cshtml

<table class="table">
    <thead>
    <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Price</th>
    </tr>
    </thead>
    @foreach (var product in Model)
    {
        <tr>
            <td>@product.ID</td>
            <td>@product.Name</td>
            <td>@product.Price $</td>
        </tr>
    }
</table>

Views/Product/Weather.cshtml
@model AspNetMVC.Models.WeatherModel
<div>
    
    <h3>Погода в @Model.City</h3>
    <table class="table">
        <thead>
        <tr class="weather">
        <th>Середня температура</th>
        <th>Погода</th>
        <th>Опис</th>
        <th>Вологість</th>       
        <th>Швидкість вітру</th>
        </tr>
        </thead>

        <tr class="weather">
         <td>@Model.Temperature °C</td>
        <td>@Model.Weather</td>
        <td>@Model.WeatherDescription</td>        
        <td>@Model.Humidity%</td>
        <td>@Model.WindSpeed м/с </td>
      
    </tr>

 
    </table>
    
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AspNetMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AspNetMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AspNetMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Consultation" asp-action="Index">Consultation</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AspNetMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>